# Basic
name:               "Wis Kojohnjaratkul"
description:        "My mediocre blog"

url:                "//wiskojo.github.io"
author:             "Wis"
github:
  username:         "wiskojo"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:month/:day/:year/:title/

# Markdown
markdown:           kramdown

# Navigation
# nav:
#  - name:           "About"
#    href:           "//kiko.gfjaru.com/about"
#  - name:           "Download"
#    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
